name: Excel to SBOL Linting

on:
  # push:
  #   branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: any
          # Additional arguments to pass to flake8, default "." (current directory)
          args: "--ignore=E501 ."
  # flake8_py3:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.9.5
  #         architecture: x64
  #     - name: Checkout Excel2SBOL
  #       uses: actions/checkout@master
  #     - name: Install flake8
  #       run: pip install flake8
  #     - name: Change directories
  #       run: cd ./excel2sbol
  #     - name: Run flake8
  #       uses: suo/flake8-github-action@releases/v1
  #       with:
  #         checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
