name: Shell Scripts Unit Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Install Pytest and excel2sbol
        run: |
          python -m pip install pytest
          python -m pip install -e ./excel2sbol
      - name: Test with pytest
        run: pytest -vv